CREATE EXTENSION pgcrypto;

DROP TABLE IF EXISTS "contact";


CREATE TABLE contact (
  id uuid NOT NULL DEFAULT gen_random_uuid(), --The record ID. Stored in the edu.uark.dataaccess.entities:BaseEntity#id property. See also the named constant defined in edu.uark.dataaccess.entities:BaseFieldNames that is used for Java <-> SQL mappings.
  ownerid character varying(38) NOT NULL DEFAULT(''), --Stored in the edu.uark.models.entities:ProductEntity#lookupCode property. See also the named constant defined in edu.uark.models.entities.fieldnames:ProductFieldNames that is used for Java <-> SQL mappings.
  name character varying(99),
  phonenumber int NOT NULL DEFAULT(0), --Stored in the edu.uark.models.entities:ProductEntity#count property. See also the named constant defined in edu.uark.models.entities.fieldnames:ProductFieldNames that is used for Java <-> SQL mappings.
  createdon timestamp without time zone NOT NULL DEFAULT now(), --Stored in the edu.uark.dataaccess.entities:BaseEntity#createdOn property. See also the named constant defined in edu.uark.dataaccess.entities:BaseFieldNames that is used for Java <-> SQL mappings.
  CONSTRAINT contact_pkey PRIMARY KEY (id)
) WITH (
  OIDS=FALSE
);

--DROP INDEX ix_contact_phonenumber;

CREATE INDEX IF NOT EXISTS ix_contact_ownerid
  ON contact
  USING btree(ownerid);

  INSERT INTO contact (ownerid, name, phonenumber) VALUES ( --id and createdon are generated by default.
          'ownerid'
        , 'name'
       , 100)
  RETURNING id, createdon;

  INSERT INTO contact (ownerid, name, phonenumber) VALUES ( --id and createdon are generated by default.
          'ownerid2'
        , 'name2'
       , 10000)
  RETURNING id, createdon;

  INSERT INTO contact (ownerid, name, phonenumber) VALUES ( --id and createdon are generated by default.
          'ownerid3'
        , 'name3'
       , 10003738)
  RETURNING id, createdon;

  INSERT INTO contact (ownerid, name, phonenumber) VALUES ( --id and createdon are generated by default.
          'ownerid3'
        , 'name7'
       , 1)
  RETURNING id, createdon;

  INSERT INTO contact (ownerid, name, phonenumber) VALUES ( --id and createdon are generated by default.
          'ownerid3'
        , 'na'
       , 1000338)
  RETURNING id, createdon;

--SELECT * FROM contact;

--DELETE FROM contact;
