CREATE EXTENSION pgcrypto; --Allows PostgreSQL to understand UUIDs. Only have to create the extension once for a database.

DROP TABLE employee;

CREATE TABLE employee (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employeeid character varying(32) NOT NULL DEFAULT(''),
  firstname character varying(128) NOT NULL DEFAULT(''),
  lastname character varying(128) NOT NULL DEFAULT(''),
  password character varying(512) NOT NULL DEFAULT('')
) WITH (
  OIDS=FALSE
);

CREATE INDEX ix_employee_employeeid
  ON employee
  USING btree(employeeid);
RETURNING id;

INSERT INTO employee (employeeid, firstname, lastname, password) VALUES ( --id is generated by default.
       'jcconnol'
	 , 'John'
	 , 'Connolly'
     , 'haha')
RETURNING id;

SELECT * FROM employee;

--DELETE FROM employee;