CREATE EXTENSION pgcrypto; --Allows PostgreSQL to understand UUIDs. Only have to create the extension once for a database.

DROP TABLE users;

CREATE TABLE users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usersid character varying(32) NOT NULL DEFAULT(''),
  firstname character varying(128) NOT NULL DEFAULT(''),
  lastname character varying(128) NOT NULL DEFAULT(''),
  password character varying(512) NOT NULL DEFAULT('')
) WITH (
  OIDS=FALSE
);

CREATE INDEX ix_users_usersid
  ON users
  USING btree(usersid);

INSERT INTO users (usersid, firstname, lastname, password) VALUES ( --id is generated by default.
       'jcconnol'
	 , 'John'
	 , 'Connolly'
     , 'haha')
RETURNING id;

SELECT * FROM users;

--DELETE FROM users;
