CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION pgcrypto;


DROP TABLE IF EXISTS "users";

CREATE TABLE users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usersid int NOT NULL DEFAULT(0),
  firstname character varying(128) NOT NULL DEFAULT(''),
  lastname character varying(128) NOT NULL DEFAULT(''),
  password character varying(512) NOT NULL DEFAULT(''),
  createdon timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
) WITH (
  OIDS=FALSE
);

CREATE INDEX IF NOT EXISTS ix_users_usersid
  ON users
  USING btree(usersid);

  INSERT INTO users (usersid, firstname, lastname, password) VALUES ( --id and createdon are generated by default.
            100
          , 'test'
         , 'test'
       , 'test')
    RETURNING id, createdon;

  INSERT INTO users (usersid, firstname, lastname, password) VALUES ( --id and createdon are generated by default.
            101
          , 'ashley'
         , 'cain'
       , 'ashleycain')
    RETURNING id, createdon;

  INSERT INTO usesrs (usersid, firstname, lastname, password) VALUES ( --id and createdon are generated by default.
            102
          , 'test'
         , 'test'
       , 'test')
    RETURNING id, createdon;

  INSERT INTO users (usersid, firstname, lastname, password) VALUES ( --id and createdon are generated by default.
            103
          , 'John'
         , 'connolly'
       , 'whatever')
    RETURNING id, createdon;

--SELECT * FROM contact;

--DELETE FROM contact;
